const { StatusCodes } = require('http-status-codes');
const teamService = require('../services/team');

// nÃ£o precisa do next e try catch por conta do rescue
exports.createTeam = async (req, res) => {
  const team = await teamService.create(req.body);
  res.status(StatusCodes.CREATED).json({ success: true, team });
};

exports.getAllTeams = async (_req, res) => {
  const teams = await teamService.getAll();
  res.status(StatusCodes.CREATED).json({ success: true, teams });
};

exports.getTeamById = async (req, res) => {
  const team = await teamService.getTeamById(req.params.id);
  res.status(StatusCodes.CREATED).json({ success: true, team });
};

exports.updateTeam = async (req, res) => {
  const team = await teamService.update(req.params.id, req.body);
  res.status(StatusCodes.CREATED).json({ success: true, team });
};

exports.deleteTeam = async (req, res) => {
  await teamService.delete(req.params.id);
  res.status(204).json({ success: true });
};
